server:
      port: 8080
      contextPath: /uaa
security:
      user:
        password: password


#Spring
spring:
    profiles:
      active: dev
    devtools:
      livereload:
        enabled: true
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
spring.datasource.validationQuery: SELECT 1
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
spring.datasource.url: jdbc:mysql://localhost:3306/duhire-users
spring.datasource.username: duhire
spring.datasource.password: password